version: '3.8'

services:
  db:
    image: postgres:11.13 
    volumes:      
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    restart: always
    command: -p $DB_PORT
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: "./api"
    environment:
      - PORT=$API_PORT
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_DIALECT=$DB_DIALECT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    environment:
      - NODE_ENV=$CLIENT_NODE_ENV
      - PORT=$CLIENT_PORT
      - REACT_APP_API_HOST
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    
volumes:  
 postgres_data:

networks:
  services-network:
    name: services-network
    driver: bridge

  